spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.MySQLDialect

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/flashcard
        username: root
        password: root
